name: Build and Deploy Claude Server

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Python Claude Server version"
        required: true
        default:
      branch:
        description: "Branch to build from"
        required: true
        default: "claude-engine"
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Create/Update requirements.txt
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install pipreqs
          pipreqs . --force

      - name: Install dependencies
        shell: pwsh
        run: |
          pip install -r requirements.txt

      - name: Install general dependencies
        shell: pwsh
        run: |
          pip install pyinstaller
          pip install uvicorn
          pip install Pillow
      - name: Convert assets
        shell: python
        run: |
          from PIL import Image
          img = Image.open("assets/icon.png")
          img.save("assets/icon.ico")
      - name: Update Version
        shell: pwsh
        run: |
          Write-Host "Current content:"
          Get-Content version.py

          $versionPattern = 'version = "[^"]*"'
          $newVersion = 'version = "' + "${{ github.event.inputs.version }}" + '"'

          $content = Get-Content version.py -Raw
          $newContent = $content -replace $versionPattern, $newVersion

          Set-Content -Path version.py -Value $newContent -Force

          Write-Host "Updated content:"
          Get-Content version.py

          if ($LASTEXITCODE -ne 0) {
              Write-Error "Failed to update version.py"
              exit 1
          }
      - name: Commit version changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add version.py
          git commit -m "Update version to ${{ github.event.inputs.version }}"
          git push origin ${{ github.ref }}

      - name: Build exe
        run: |
          pyinstaller --onefile --icon=./assets/icon.png --distpath ./dist --name "Claude Server.exe" main.py

      - name: Create zip file
        shell: pwsh
        id: version
        run: |
          $VERSION = ${{github.event.inputs.version}}
          7z a "Claude Server-$VERSION.zip" ./dist/"Claude Server.exe"
          echo "VERSION=$VERSION" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Upload zip file
        uses: actions/upload-artifact@v4
        with:
          name: Claude-Server-${{ github.event.inputs.version }}.zip
          path: "Claude Server-${{ github.event.inputs.version }}.zip"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: claude-v${{ github.event.inputs.version }}
          release_name: Release v${{ github.event.inputs.version }}
          draft: true
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Claude Server-${{ github.event.inputs.version }}.zip
          asset_name: Claude-Server-${{ github.event.inputs.version }}.zip
          asset_content_type: application/zip
