name: Build and Deploy Claude Server

on:
  push:
    branches:
      - claude-engine  

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9 

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          if (-not (Test-Path requirements.txt)) { Write-Error "requirements.txt missing"; exit 1 }
          pip install -r requirements.txt

      - name: Install pyinstaller
        run: pip install pyinstaller

      - name: Build exe
        run: |
          pyinstaller --onefile --distpath ./dist --name "Claude Server.exe" main.py

      - name: Create zip file
        shell: pwsh
        run: |
          $VERSION = git describe --tags --always
          7z a "Claude Server-$VERSION.zip" ./dist/"Claude Server.exe"

      - name: Upload zip file
        uses: actions/upload-artifact@v4
        with:
          name: Claude-Server-${{ steps.version.outputs.VERSION }}.zip
          path: "Claude Server-${{ steps.version.outputs.VERSION }}.zip"
