name: Generate Requirements

on:
  push:
    branches:
      - claude-engine  

jobs:
  generate-requirements:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Getting Requirements
        run: |
          pip install pipreqs
          pipreqs . --force


      - name: Commit and push requirements.txt
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add requirements.txt
          git commit -m "[AUTOMATED] Update requirements.txt"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      